domain: beckenboden-friedrichshagen.de       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://beckenboden-friedrichshagen.de  # the base hostname and protocol for your site, e.g. http://example.com
repository: carineschippers/carineschippers.github.io

description: |
  Beckenboden Physiotherapie in Friedrichshagen. Carine Schippers

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown
highligher: rouge

exclude:
  - beckenphysio.sublime-project
  - beckenphysio.sublime-workspace
  - Gemfile
  - Gemfile.lock

collections_dir: _content

collections:
  indikationen:
    order:
      - schwangerschaft.md
      - inkontinenz.md
      - beckenschmerzen.md
      - maenner.md
      - blasenbeschwerden.md
      - senkungsbeschwerden.md
  behandlungen:
    order:
      - einzeltherapie.md
      - kleingruppen.md
      - rektusdiastase.md
      - coaching.md
      - massagen.md
      - preise.md
  rows:
    order:
      - top-foto.html
      - willkommen.md
      - aktuelles.html
      - der-beckenboden.md
      - indikationen.html
      - beckenboden-check.md
      - massage.html
      - behandlung.md
      - behandlungen.html
      - ueber-mich.md
      - kontakt.html

permalink: /:title
