domain: beckenboden-friedrichshagen.de       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://beckenboden-friedrichshagen.de  # the base hostname and protocol for your site, e.g. http://example.com
repository: carineschippers/carineschippers.github.io

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown
highligher: rouge

exclude:
  - beckenphysio.sublime-project
  - beckenphysio.sublime-workspace
